### ISSUE TITLE
Missaligned buttons in PF2e

### ISSUE THREAD

**Issue by Turqueso** [DarKDinDoN/share-media#12]
In version 0.0.12 the buttons are missaligned in PF2e. I've updated to 0.0.13 but the problem remains. I tested dnd5e and they look fine
![image](https://user-images.githubusercontent.com/4932347/165866324-9a5413e4-f78a-44d9-b855-13c0ba675755.png)
![image](https://user-images.githubusercontent.com/4932347/165866386-d92e98d3-4d25-498b-8b15-046a4376ea71.png)
![image](https://user-images.githubusercontent.com/4932347/165866398-227c55b0-8a3c-484d-88c4-6120f1e2716a.png)

**Comment by DarKDinDoN** [comment]
Hello,

Thx for the report!
Seems that PF2 use its own styling for journal notes.
[0.0.14](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.14) should fix this.
