### ISSUE TITLE
Feature Request: Add hud interaction for show token and actor image

### ISSUE THREAD

**Issue by p4535992** [DarKDinDoN/share-media#14]
I would like some kind of HUD-level action to be added to the single token as was done in its time with https://github.com/zeel01/TokenHUDArtButton, but integrating it with your dialogue for choose specific players to visualize.

A very low priority request.

**Comment by DarKDinDoN** [comment]
Hello,

Thx for suggesting new features.

The basic is now implemented with [0.0.20](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.20)

**Comment by p4535992** [comment]
Hi sorry to bother , it is possibile on the hud to add the option to show the image to a specific player like you already done on the journals ?

**Comment by DarKDinDoN** [comment]
@p4535992 Sure thing, this is live with [0.0.21](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.21)
