### ISSUE TITLE
Dark Glass Background option for sharing media (images, mostly)

### ISSUE THREAD

**Issue by apoapostolov** [DarKDinDoN/share-media#15]
The current blurred zoomed image background seems to be very distracting for certain bright images; why not implement a darken the background effect with some nice animation (such as a soft, slow black fog effect) that would make any image, even darker ones, pop up and be very easy to focus at.

**Comment by DarKDinDoN** [comment]
Hello @apoapostolov,

Thx for suggesting features.
Can you provide some examples?
- Bright image example
- Darken background example

Thx

**Comment by apoapostolov** [comment]
Hello, CSS example here: https://codepen.io/apoapostolov/pen/VwQrJoY

**Comment by DarKDinDoN** [comment]
Ah, I see now what you mean.

It's not really about dark or bright images. The blur should be "blurry" enough, so you can read the actual image.
It is more about transparent images for which the readability might be more difficult.

Tell me if that's correct? Otherwise, please provide an actual example of "distracting" situations.

**Comment by apoapostolov** [comment]
For now, I will use Custom CSS to at least remove the blur cover. 
```
#fullscreen-layer .background { display:none !important; }
```
I think I can do a full screen blur if I force an image across the screen that is static, I will probably test this next.

**Comment by DarKDinDoN** [comment]
@apoapostolov [0.0.22](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.22) should fix this issue.

If the image can be transparent (png or webp) or is a video, a black, blurred background is displayed instead.
Otherwise, the same image is displayed in the background (and blurred).
