### ISSUE TITLE
Stream Support

### ISSUE THREAD

**Issue by brunocalado** [DarKDinDoN/share-media#16]
Hi.

Can you add an option to prevent a user from receive a shared media when you click you show all?

This is useful when you stream one user and don't want to shared image to show for the stream user.

![image](https://user-images.githubusercontent.com/4999783/171937675-f257eab7-5c9d-433e-bf68-59043ed98bcb.png)

tks

**Comment by DarKDinDoN** [comment]
Hello @brunocalado 

Can you be more specific please?
It should already be the case. There should be two buttons, "share to all players" and "share to some players".

**Comment by DarKDinDoN** [comment]
Also, the window in the screenshot is not from share-media.

**Comment by brunocalado** [comment]
Yes. But, it's same from share media button.
![image](https://user-images.githubusercontent.com/4999783/171945677-cf22d0f5-554c-4098-a575-7d52be9da646.png)

If I share the embbed media all connected users will receive this imagem. But, there is one user used for stream that should not receive it.

I can just unselect it every time. But, I wonder if you can't make this easier.
![image](https://user-images.githubusercontent.com/4999783/171945942-2727319e-c86a-4652-a99e-c20f98f03bd0.png)

Examples
- Create an option in settings to always avoid the user
- Let you pick a default for the check box

**Comment by DarKDinDoN** [comment]
I'll have to think about that.
Out of curiosity, why don't you want your stream to show medias?

**Comment by brunocalado** [comment]
> 

1. When make a safe stream you can use art without permission
2. When I can: It's annoying to go to OBS and remove the image from there. The foundry runs inside OBS, I'm not recording a browser window.

**Comment by DarKDinDoN** [comment]
@brunocalado a blacklist feature is now live with [0.0.23](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.23)

**Comment by brunocalado** [comment]
> @brunocalado a blacklist feature is now live with [0.0.23](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.23)

Thank you.
