### ISSUE TITLE
Full Screen Under the UI

### ISSUE THREAD

**Issue by brunocalado** [DarKDinDoN/share-media#18]
Hi!

Can you make the full screen image/video show over everything? 
![image](https://user-images.githubusercontent.com/4999783/172075275-e9b199f6-dd71-4bad-9166-46bc0c2a2bb8.png)

Tks

**Comment by DarKDinDoN** [comment]
@brunocalado 
I probably could. But only as a game wide setting. Not a "per media" setting.

Would that be alright?

**Comment by brunocalado** [comment]
OH yeah. Very very good. Thank you.

https://user-images.githubusercontent.com/4999783/172157258-b7fcd377-e1b6-492a-a10a-2b605500a232.mp4

I just wonder if you can remove these UI buttons. You could dismiss with a left click or double click.
![image](https://user-images.githubusercontent.com/4999783/172157349-dc76d8e5-c791-4ecf-9f9c-9a670b26d95f.png)

**Comment by DarKDinDoN** [comment]
@brunocalado 
UX wide, I can't really get rid of the buttons.
I tweaked the CSS a little, so the buttons are transparent until hovered: [0.0.26](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.26)

Also keep in mind that it is very dependent on the background, which in your case black (worse case scenario)

**Comment by DarKDinDoN** [comment]
If everything tends to be dark, almost black in your game (for whatever reason), you can tweak the CSS with this module: https://github.com/cswendrowski/FoundryVTT-Custom-CSS

**Comment by brunocalado** [comment]
> @brunocalado UX wise, I can't really get rid of the buttons. 
This (https://github.com/DM-miX/scene-transitions) module did that if you want a snippet. You can click to remove the fullscreen image.

It's nice the transparent button. Thank you again.
