### ISSUE TITLE
Improve Hover Controls

### ISSUE THREAD

**Issue by benbarbour** [DarKDinDoN/share-media#2]
Hi - love this! My one issue is that the hover controls don't work very well on tiny images. For example:

![image](https://user-images.githubusercontent.com/487715/150037698-14ba54d3-57ac-433f-95eb-417bfe5f2a12.png)

Not sure what the best way to fix them is though... maybe an option to just have the buttons and put the decisions that are currently in the hover menus into the popups (and/or behind a modifier key)?

**Comment by DarKDinDoN** [comment]
Hey,

Thx for the report.
Can you export the journal note and attach it to this issue?

**Comment by DarKDinDoN** [comment]
@benbarbour Hello,
Should be fixed with 0.0.4
