### ISSUE TITLE
API

### ISSUE THREAD

**Issue by brunocalado** [DarKDinDoN/share-media#20]
Hi.

Is it possible to expose some of the API?

Examples:
```js
sharemedia.Fullscreen('image.webp')
sharemedia.ShowAll('image.webp')
sharemedia.ShowAll('image.webp')
```

This is useful to trigger macros. 

Tks

**Comment by DarKDinDoN** [comment]
@brunocalado Hi, a basic implementation has been deployed with [0.0.7](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.27)

The API doc is here: https://github.com/DarKDinDoN/share-media/blob/main/API.md

I'll let you close this issue if you find the API capabilities enough for you.

**Comment by brunocalado** [comment]
tks
