### ISSUE TITLE
[Suggestion] For the implementation of the API follow the best practices

### ISSUE THREAD

**Issue by p4535992** [DarKDinDoN/share-media#21]
For the API integration can i suggest fo follow the [League best practices](https://foundryvtt.wiki/en/development/guides/package-best-practices) ?

Basically replace the:
```
window["share-media"].API
```
with:
```
game.modules.get('share-media')?.api
```
or you can use both, in some old module i just do:

```
 window["XXX"].API = game.modules.get('XXX')?.api
```

**Comment by DarKDinDoN** [comment]
@p4535992 Thx for the tip.
Share media can not be accessed though: `game.modules.get('share-media').API`
