### ISSUE TITLE
[Feature Suggestion] Double-click the layer name to load image (in the Which bounding tile to display UI)

### ISSUE THREAD

**Issue by drswoboda** [DarKDinDoN/share-media#23]
Is it possible to add the ability to just double-click the layer name in the "Which bounding tile to display..." UI dialog?

It would be a bit faster and more efficient with less mousing around.
![Foundry_Virtual_Tabletop_3EKj6WnPPP2](https://user-images.githubusercontent.com/7105711/183105227-7af135a8-8d67-49c5-80d4-a610c388032d.png)
.
Thanks,
David

**Comment by DarKDinDoN** [comment]
Hi David,

Thank you for your suggestion.
It's a great idea that is now implemented with [0.0.29](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.29)
