### ISSUE TITLE
Can Share media on hud ask where to share?

### ISSUE THREAD

**Issue by jacksands** [DarKDinDoN/share-media#24]
I wish to share some token media on the Canvas, not on a journal, but using context options on tokens became difficult because other modules also add their own options to then, now there are too many...

Can the hud options windows add an option to Were to share?

also, if that is possible, perhaps the context of the actors and items can be only "share media options" that opens this dialog window, that may be an option on settings for those how like it, but for me that would make for a much cleaner context menu.

Anyway great module! I use it a lot!  Thanks!

![image](https://user-images.githubusercontent.com/7229143/184010153-469a9d60-0be6-487c-b037-a44d590728af.png)

**Comment by DarKDinDoN** [comment]
@jacksands hello
I appreciate you taking an interest in Share media.

This will be implemented with Foundry V10:
- Click the token HUD will show a dialog with share options
- Only one sidebar context entry when right-clicking an actor or an item. This opens a dialog with share options as well

Will be release once Foundry V10 goes official.
