### ISSUE TITLE
[Feature Request] Option to show actor/token title when displaying image?

### ISSUE THREAD

**Issue by JulieWinchester** [DarKDinDoN/share-media#26]
It would be great to be able to optionally show an actor or token's name along with the image when you display it to players in fullscreen or windowed modes. Even if it was a module config setting, that would be very useful. Often I want to show NPC portraits to players, and it's helpful to show the names at the same time so I don't have to spell the name aloud for players' notes. I like the fullscreen display in this module better than what Theatre Inserts provides, except for not having the names. Thanks for considering the request, this is a great module!

**Comment by DarKDinDoN** [comment]
Hello @JulieWinchester 

Thank you for taking an interest in Share Media.
Your request is now implemented with [0.0.31](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.31)
