### ISSUE TITLE
Monk enhanced journals and V10

### ISSUE THREAD

**Issue by jacksands** [DarKDinDoN/share-media#27]
Hi!  tks again for the module!

Question.. in v9 it worked flawlessly with monk enhanced journals, but not in v10...  

Is that possible?

Best regards!
Erich
![Untitled-1](https://user-images.githubusercontent.com/7229143/190150489-b87bb8de-9938-4d55-a86d-7551e9c14e5c.png)

**Comment by DarKDinDoN** [comment]
Hi @jacksands 

Thank you for taking the time to report this.
Monk's Enhanced Journal creator had to change a lot of code to make his module V10 compatible.
That is why it didn't work with  FVTT V10.

[0.0.32](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.32) should fix that situation.
Although, be warned, I didn't test all custom Enhanced Journal sheets.

**Comment by jacksands** [comment]
Fully working!  tested on all sheets! 

it took a while to test!  =D

TKS!!!
