### ISSUE TITLE
Issue with journal header images in pf2e premium modules (Abomination Vaults)

### ISSUE THREAD

**Issue by ChaseDonnally** [DarKDinDoN/share-media#28]
The Share Media module causes the section header images in journal entries for the Abomination Vaults module to disappear. They should look like this:
 
![image](https://user-images.githubusercontent.com/47797620/190875373-99435c4d-4f14-49ec-a698-d1720d8978e2.png)

But instead show up like this:
![image](https://user-images.githubusercontent.com/47797620/190875395-af6b0769-527e-4139-b655-9d10ce841bf7.png)

Here's the HTML for how these sections are formatted if that helps in troubleshooting:

```
<section class="box-text encounter">
    <header>
        <img src="modules/pf2e-abomination-vaults/assets/journal-images/icons/encounter/haunt.webp" width="100" style="">
        <section>
            <h2>Haunt</h2>
            <h2>Moderate 1</h2>
        </section>
        <section>
            <div>
                <p>@Actor[8VXEF3cnjzcokCTL]{Stonescale Spirits}</p>
            </div>
            <p>80 XP</p>
        </section>
    </header>
    <article>
        <p>Lorem ipsum etc</p>
    </article>
</section>
```

**Comment by DarKDinDoN** [comment]
Hello @ChaseDonnally 

Thank you for reporting this.
Share media won't try to process media that are direct descendants of a header tag anymore.

[0.0.34](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.34) should fix your issue.
