### ISSUE TITLE
Macro for fast clearing of bounding tile

### ISSUE THREAD

**Issue by saeldion** [DarKDinDoN/share-media#29]
As the title says. It would be nice to have a macro that clears the bounding tile so that you don't have to go into the "Tiles" menu every time you want to clear it.

Could probably figure it out. But would be nice if it was included with the module.

**Comment by DarKDinDoN** [comment]
@saeldion Hi, thank you for reporting this.

I totally understand the UX issue of clicking multiple times to get a single bounding tile clear.

[0.0.35](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.35) added an API method you can use in a macro:

```
game.modules.get('share-media').API.clearBoundingTile()
```

I'm not quite comfortable creating a dedicated compendium just for this.
A lot of modules do. It can be packed, really fast, in the compendium section of FVTT.
