### ISSUE TITLE
Kanka broken on v10

### ISSUE THREAD

**Issue by zdaar** [DarKDinDoN/share-media#31]
Hello,

It seems that it does not work anymore on v10 with kanka.

![image](https://user-images.githubusercontent.com/4218386/191466669-e806d032-25e5-4a84-92ff-0c6c1014ec84.png)

Could you take a look ?
Here was the former issue on v9 back to when you fixed it

https://github.com/DarKDinDoN/share-media/issues/7

Thanks in advance ! <3

**Comment by DarKDinDoN** [comment]
Hi @zdaar [0.0.36](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.36) should restore compatibility with Kanka.

**Comment by zdaar** [comment]
Merci @DarKDinDoN t'es le meilleur :)
