### ISSUE TITLE
[Feature Request] Connect an audio file to the image when is shared

### ISSUE THREAD

**Issue by p4535992** [DarKDinDoN/share-media#32]
When I share an image I typically enable audio to be associated with it, is it possible to add to the context menu the ability to associate audio with it when it is shared to players ?

Something like "show image with audio" . 
The problem is that I don't know how to make associate audio to the image dynamically... for my use case after choose to share the image a simple dialog asking me if I want to associate an audio with the ability to select it is more than enough.

NOTE: I am talking about associating only a single track.

**Comment by DarKDinDoN** [comment]
Hello,

Thx for suggesting this feature.

Share Media doesn't store any flag at the media level. So I can't really bind an audio file with a media.
You'll have to select the same track again and again each time you want to share the same image.

So having a button the user have to click just to display a dialog with a list of tracks isn't really helpful (even so if there are a lot of tracks). Going to the track list in the sidebar and starting "manually" a track might even be "faster".

What are you thoughts?

**Comment by p4535992** [comment]
I hoped you had some stroke of genius. Maybe thinking in reverse ? We do not have a flag for the image , but we do have the url , so maybe set on the audio track a flag on which to set a the url of the image as a comparison value ?
That is I set in an audio track with the flag e.g. "linked_image_source" with the url value of the source image and when I do the share of the image a check starts to retrieve the audio track with that flag set ....

No it's too complicated... it's still faster the current manual solution... forget it...

**Comment by DarKDinDoN** [comment]
I might be able to add a button to choose a track and then edit the raw source to embed the track ID in a data attribute.

But I fear that UX wise, every time you choose a track, the HTML gets saved, the editor scroll to top, yadii, yadaa. Things to overcome...
Yeah, quite complicated.
