### ISSUE TITLE
Full Screen share influenced by scene darkness

### ISSUE THREAD

**Issue by jacksands** [DarKDinDoN/share-media#33]
Hi! first tanks for the module, I use it a lot!

But I have a issue, in full screen sharing, at least immersive mode, the darkness of the scene interfere with the darkness of the image...

Can this be corrected to always show the image clearly?

I have add a print to show the difference.

Tks

Erich

![111](https://user-images.githubusercontent.com/7229143/202873117-18bcc160-4443-4463-af78-566d29822911.png)   darkness level 100%  (1)

![222](https://user-images.githubusercontent.com/7229143/202873121-4b9802b8-dc86-4d7e-a498-5cb2ecd43825.png)   darkness level 0%  (0)

**Comment by DarKDinDoN** [comment]
Hello,
There is a setting for that exact purpose 😸

**Comment by jacksands** [comment]
Wow!  really sorry!  my mistake!
