### ISSUE TITLE
Sharing Images - Sizing Issues

### ISSUE THREAD

**Issue by ChaseDonnally** [DarKDinDoN/share-media#34]
When sharing a lower resolution image, could there be a setting such that the popout defaults to be no larger than the actual size of the image? Currently if you share a lower-res image it blows it up in the popout which makes the quality look lower.

Thanks!

**Comment by DarKDinDoN** [comment]
Hello @ChaseDonnally,

Thanks for using Share Media.
Unfortunately, that is a foundry issue. Share Media uses the default foundry popout behavior.
