### ISSUE TITLE
Version 0.0.41 reinstalls itself everytime (Updated Manifest URL)

### ISSUE THREAD

**Issue by struckyCZ** [DarKDinDoN/share-media#36]
![image](https://github.com/DarKDinDoN/share-media/assets/80347865/0c885ade-632b-4385-9d2f-4cfbba0756c7)

**Comment by DarKDinDoN** [comment]
Oups, should be fixed. Might require uninstall and reinstall first.
Thx for reporting this!

**Comment by struckyCZ** [comment]
It's okay now even without the reinstall. Thanks!
