### ISSUE TITLE
Token Image Vanishes When Sharing to Scene from Token HUD

### ISSUE THREAD

**Issue by Ranimara** [DarKDinDoN/share-media#37]
Hello!  I found a bug today while experimenting with the token HUD buttons on a scene where I use a bounding tile.  When I shared the token image to the bounding tile, and then switched to sharing the actor image, the image on the token itself vanished.  I was able to restore it by just deleting the token and dragging the actor back out again.

**Foundry Version:** 11
**Share Media Version:** 0.0.41

**Steps to Reproduce**
1. Drag an actor to a scene that uses a bounding tile
2. Right-click the actor token to open the context menu
4. Left-click "Share Token Image" -> "Share on the Scene (cover)" - The actor token is now shared on the canvas
5. Right-click "Share Token Image" -> "Share on the Scene (cover)" - The actor image is now shared on the canvas, and the token image has vanished from the token
![ShareMediaBug Step 4](https://github.com/DarKDinDoN/share-media/assets/37903989/c8b80dc5-5efc-477d-99c4-e440975ba79a)
![ShareMediaBug Step 5](https://github.com/DarKDinDoN/share-media/assets/37903989/0d4bc4f5-30bd-4aee-9d50-8c234206764a)

**Comment by DarKDinDoN** [comment]
Hi,
Thank you for taking the time to report this.
This should be fixed with: [0.0.42](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.42) 🚀
