### ISSUE TITLE
Request : Share button for tile

### ISSUE THREAD

**Issue by uniwars** [DarKDinDoN/share-media#39]
Hi, could you add this feature for tile please ?
![image](https://github.com/DarKDinDoN/share-media/assets/65986545/cd046c1b-c49d-4222-8d40-e7bd5df6f4c5)
if possible on the bottom left of tile HUD since the right is pretty busy with other modules

**Comment by DarKDinDoN** [comment]
Hi,

This is now implemented with: [0.0.49](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.49)
