### ISSUE TITLE
compatibility with GMnotes

### ISSUE THREAD

**Issue by Orionox** [DarKDinDoN/share-media#4]
the popups to share media does not appear in GM note

**Comment by DarKDinDoN** [comment]
Hello,

I would love to help and support the GMnotes module.
Unfortunately, per my tests, the module is not compatible with the latest version of foundry (9.255) and 5e (1.5.7).

I created an issue on the relevant repo, and I am waiting for a fix before trying to make share-media compatible with Gmnotes: https://github.com/syl3r86/gm-notes/issues/28

**Comment by DarKDinDoN** [comment]
Someone was kind enough to provide a link to a working version of GM Notes (https://github.com/syl3r86/gm-notes/issues/28#issuecomment-1074226836)

Share Media is now compatible with GMNotes 🥳
