### ISSUE TITLE
Interaction with Foundry Video Bar in Full Screen

### ISSUE THREAD

**Issue by claycle** [DarKDinDoN/share-media#40]
## The Problem 

We use the Foundry chat/video and to keep my eye-line more direct towards the players, I position the video bar at the top of the screen. Foundry elements move downward to accommodate the chat/video bar. However, if I use Share Media to do a full-screen share, the Dismiss Media button will appear beneath the Foundry video bar and is not accessible.

## The Solution(s)

Ideally, Share Media should not place the Dismiss Media button beneath any Foundry elements. Either

1. Share Media detects, like other Foundry elements, that the video bar is at the top of the screen and adjusts the height of the media to fit; or
2. Share Media allows the user to configure the position of the Dismiss Media button either at the top or the bottom of the media overlay (or, alternatively, it automatically places the button in the most appropriate position); or
3. Share Media intercepts a keystroke (ESC?) to dismiss the media overlay.

![Screenshot 2024-02-28 at 4 22 09 PM](https://github.com/DarKDinDoN/share-media/assets/419840/11556296-6180-40fb-859f-1b6dd6d1b8f8)
![Screenshot 2024-02-28 at 4 22 18 PM](https://github.com/DarKDinDoN/share-media/assets/419840/1b854afb-1b06-4990-a4d4-dd9655147e13)

**Comment by DarKDinDoN** [comment]
Button can now be placed at the bottom of the screen with: [0.0.50](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.50)
