### ISSUE TITLE
[Feature Request] Align images to Bounding Tile rotation

### ISSUE THREAD

**Issue by pj-squirrel** [DarKDinDoN/share-media#42]
Greetings, just stumbled upon this amazing module and already used it for a bit.

I mainly want to use this modules on my players' landing page to show them different sceneries but not all the design elements on my landing page are perfectly straight, so it would be amazing if I could rotate the Bounding Tiles I've created to align the image to my landing page.

At the moment going into the tile and applying a rotation angle has no effect on how the shown image is presented, it just stays the way it is.

Foundry Version: 11
Share Media Version: 0.0.50

Thanks!

**Comment by DarKDinDoN** [comment]
Hi, thank you for taking to time to write this feature request.
It is now implemented with: [0.0.51](https://github.com/DarKDinDoN/share-media/releases/tag/0.0.51)
