### ISSUE TITLE
Help with Macro for share Fullscreen immersive mode all players...

### ISSUE THREAD

**Issue by jacksands** [DarKDinDoN/share-media#44]
Please help me creating a macro for a full-screen immersive mode for all players!?

![image](https://github.com/DarKDinDoN/share-media/assets/7229143/09078445-fc15-460b-8ef5-aa879d8a3593)

My players travel through a wormhole on the adventure, and a macro to activate it instead of manually would help me a lot!!!

by the way tks for the module!  amazing!!!

just a note, can you add the ability to use Token Magic FX on the tiles?  it is possible?

**Comment by DarKDinDoN** [comment]
Hi, there is an API documentation here for that: https://github.com/DarKDinDoN/share-media/blob/main/API.md#fullscreen

Basically:
```javascript
game.modules.get('share-media').API.shareFullscreenMediaToAll(url, title = "", immersive = true, loop = false, mute = true)
```

As for Token Magic FX, I'm afraid I can't do that. The creator of Token Magic FX might try on his side.

**Comment by jacksands** [comment]
Wow that was fast!!!

tks!
