### ISSUE TITLE
Share Journal Image, Actor/Item Artwork, etc.

### ISSUE THREAD

**Issue by patrickburk1988** [DarKDinDoN/share-media#5]
Love this module! I was wondering if you had any plans to expand the sharing behavior to non-embedded journal images (i.e. under `Image` in the journal window header) and the pop-up artwork for actors/items (i.e. under `View Character Artwork` or `View Item Artwork` when right-clicking an actor/item in the sidebar)?

**Comment by patrickburk1988** [comment]
I think it might be a default function. I see it whenever I right-click an actor/item in the sidebar, provided they have a portrait image:
![](https://i.imgur.com/ERKn7Ui.png)

Clicking it reveals a full-sized pop-up, but the option to share media isn't available:
![](https://i.imgur.com/frXdjh3.png)

**Comment by DarKDinDoN** [comment]
Thx for the details.

So actually, they are rendered in a pop out. So If I try to add buttons in there, this would add buttons is a pop out that also produce pop outs with buttons.
Button inception 🤯
Bad idea.

As for the journal image side, that's more complicated, cause the image is actually printed as a tag in the code, but as a CSS property. I'll have to investigate that, but not anytime soon, sorry.

**Comment by patrickburk1988** [comment]
To avoid the buttonception issue, what about adding context menu options to the sidebar items? It's not pretty, but something like this:
![](https://i.ibb.co/px6dM5R/image.png)
