### ISSUE TITLE
Compatibility with kanka-foundry

### ISSUE THREAD

**Issue by zdaar** [DarKDinDoN/share-media#7]
Kanka is an amazing tool (kanka.io) which offers a less bloated version of world anvil. 
Unfortunately share media is not compatible with their extended journal sheet, the popup menus do not appear !
Would you be willing to patch in compatibility ?
Thanks in advance !

**Comment by DarKDinDoN** [comment]
Hey @zdaar, thank you for suggesting features.

I'm willing to take a look, but unfortunately, it appears that I need a paid subscription to add images to text :(

![image](https://user-images.githubusercontent.com/1687854/163729072-54fad928-e17c-4f8c-8af1-79f209672d40.png)

Can you export some journal notes and link them to this issue?
Also, can you screenshot a journal note with all the images that should display the popout buttons?

**Comment by zdaar** [comment]
Hi :)

Actually you can embed images in the article with a non boosted campaign ! It just needs to be an external source, you just cant upload files to kanka itself.
See below 
![image](https://user-images.githubusercontent.com/4218386/163731625-c8ff4ac4-a01f-462b-8a87-4e27eb2018b6.png)


Thanks a lot for taking a look. 
I attached an exported journal entry (had add .txt because you cant  upload json to github comments.
[fvtt-JournalEntry-testlocation.json.txt](https://github.com/DarKDinDoN/share-media/files/8502409/fvtt-JournalEntry-testlocation.json.txt)
Here is a screenshot of the image which is not displaying a popup 
![image](https://user-images.githubusercontent.com/4218386/163731574-a1dde700-2173-40f3-bfa9-f0b93c6c6074.png)

Here is another journal entry for which it is working (nevermind the rpg-styled-ui module, the behaviour is the same. The UI doesnt apply to the kanka journal entries either for some reason)
![image](https://user-images.githubusercontent.com/4218386/163731595-2d9ffedc-0754-4ad5-a28f-2949c6af9bf2.png)

**Comment by zdaar** [comment]
Your module's hook for Hooks.on('renderJournalSheet') is fired when you open a kanka journal entry, so the problem could instead be in the wrapMedias method, maybe just not finding the right div since kanka-foundry makes extensive changes to the journal sheet.
kanka-foundry looks like compiled typescript but you can get the src folder in the actual repo :
https://github.com/eXaminator/kanka-foundry

**Comment by zdaar** [comment]
I just found out that this old deprecated module, "Show Artwork", can successfully hook on the images in the kanka-foundry module
![image](https://user-images.githubusercontent.com/4218386/163735300-a6e5bfbe-d180-412f-9c16-69bd867ee098.png)
Here is the repo (iirc its unlisted from foundry) https://github.com/wsaunders1014/showartwork

**Comment by DarKDinDoN** [comment]
0.0.9 should add compatibility with Kanka-Foundry.
Report back if you find issues.

(de rien 😉)

**Comment by zdaar** [comment]
Everything is working perfectly on that release ! Thanks alot !!

(merci encore 👍 👍 )
