### ISSUE TITLE
Suggestion: Compatibility with the module appbar

### ISSUE THREAD

**Issue by altair984** [DarKDinDoN/share-media#8]
Hi, I would like to ask you if it is possible to have compatibility with this module: "appbar". When you put a background image that covers the entire screen, it defiantly covers the bottom bar provided by the module (appbar) and you can't interact with it.

**Comment by DarKDinDoN** [comment]
Hello,

Thank you for suggesting features and improvements.
Share Media should now be compatible with AppBar.

**Comment by altair984** [comment]
yes, thanks so much :)
