### ISSUE TITLE
Option to automatically dismiss videos when playtime is over

### ISSUE THREAD

**Issue by BrotherSharper** [DarKDinDoN/share-media#9]
This way users can pop-out persona style cut-ins or quick shots of their characters doing stuff

**Comment by DarKDinDoN** [comment]
Hello,

Thank you for suggesting features.
I need to think about that. The technical implementation might not be an issue.
But the UX implementation and the interface is a bit more difficult.
There are already a lot of buttons in Share Media, I don't really want to add loop one.

**Comment by DarKDinDoN** [comment]
@BrotherSharper I ended up adding a new button afterall.
https://github.com/DarKDinDoN/share-media/releases/tag/0.0.11 add capabilities for looping options & video in fullscreen mode.
